### PR TITLE
Bind by C-type

### PR DESCRIPTION
**Pull request by cmouse**

### CODE REVIEW

**Comment by cmouse** [comment]
[2015-11-23 21:25:24] pdns_server: ../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
[2015-11-23 21:25:24] Nov 23 21:25:24 Got a signal 6, attempting to print trace: 
[2015-11-23 21:25:24] Nov 23 21:25:24 /home/travis/build/cmouse/pdns/regression-tests/../pdns/pdns_server(+0x19b69b) [0x7f91a413a69b]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7f91a21bed40]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f91a21becc9]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f91a21c20d8]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libc.so.6(+0x2fb86) [0x7f91a21b7b86]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libc.so.6(+0x2fc32) [0x7f91a21b7c32]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x100) [0x7f91a2557510]
[2015-11-23 21:25:24] Nov 23 21:25:24 /usr/lib/x86_64-linux-gnu/libodbc.so.1(+0x725a) [0x7f91a032225a]
[2015-11-23 21:25:24] Nov 23 21:25:24 ./modules/libgodbcbackend.so(_ZN14SODBCStatementC2ERKSsbiPv+0x9f) [0x7f91a0598f3f]
[2015-11-23 21:25:24] Nov 23 21:25:24 ./modules/libgodbcbackend.so(_ZN5SODBC7prepareERKSsi+0x34) [0x7f91a0598944]
[2015-11-23 21:25:24] Nov 23 21:25:24 ./modules/libgodbcbackend.so(_ZN11GSQLBackend5setDBEP4SSql+0x96) [0x7f91a05882a6]
[2015-11-23 21:25:24] Nov 23 21:25:24 ./modules/libgodbcbackend.so(_ZN12gODBCBackendC1ERKSsS1_+0xc9) [0x7f91a05879c9]
[2015-11-23 21:25:24] Nov 23 21:25:24 ./modules/libgodbcbackend.so(_ZN12gODBCFactory4makeERKSs+0x27) [0x7f91a058ac27]
[2015-11-23 21:25:24] Nov 23 21:25:24 /home/travis/build/cmouse/pdns/regression-tests/../pdns/pdns_server(_ZN17BackendMakerClass3allEb+0x60) [0x7f91a4087d80]
[2015-11-23 21:25:24] Nov 23 21:25:24 /home/travis/build/cmouse/pdns/regression-tests/../pdns/pdns_server(_ZN12UeberBackendC2ERKSs+0x1bc) [0x7f91a419f0ec]
[2015-11-23 21:25:24] Nov 23 21:25:24 /home/travis/build/cmouse/pdns/regression-tests/../pdns/pdns_server(_ZN12DNSSECKeeperC2Ev+0x3a) [0x7f91a40ddc1a]
[2015-11-23 21:25:24] Nov 23 21:25:24 /home/travis/build/cmouse/pdns/regression-tests/../pdns/pdns_server(_ZN18ChunkedSigningPipe6workerEii+0x23) [0x7f91a4165a43]
[2015-11-23 21:25:24] Nov 23 21:25:24 /home/travis/build/cmouse/pdns/regression-tests/../pdns/pdns_server(_ZN18ChunkedSigningPipe12helperWorkerEPv+0x20) [0x7f91a4165900]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7f91a2555182]
[2015-11-23 21:25:24] Nov 23 21:25:24 /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f91a228247d]

**Comment by Habbie** [comment]
I've seen that error before, it went away (briefly apparently?) when I switched to trusty. I'm blaming sqliteodbc (without argument).

**Comment by Habbie** [comment]
(It's green now!)

**Comment by cmouse** [comment]
Yeah just thought I'd make note of it

**Pull request merged**
